Update config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -31,7 +31,13 @@ jobs:
       - run:
           name: scan image
           command: |
-            ./twistcli images scan --details --address $TL_URL -u $tl_u -p $tl_p --vulnerability-threshold $TL_V $TL_OPT --compliance-threshold $TL_C $TL_IMAGE
+            ./twistcli images scan --details --address $TL_URL -u $tl_u -p $tl_p --vulnerability-threshold $TL_V $TL_OPT --compliance-threshold $TL_C $TL_IMAGE > temp.txt
+            cat temp.txt 
+            e=`cat temp.txt | grep -c "OS not supported and may be missing vulnerability data"`
+            if [ e -gt 0]; theb
+              echo "OS not supported and may be missing vulnerability data"
+              exit 128
+            fi
       #- run:
       #    name: docker login
       #    command: docker login -u $username -p $password #-e $mailaddress     
